### ISSUE TITLE
Support for Matrix 4x4 and transforms. 

### ISSUE THREAD

**Issue by richoncode** [praeclarum/ShaderGraphCoder#3]
Great library!  Thank you.  

Any plans to add support for matrix 4x4 and transforms?

**Comment by praeclarum** [comment]
Oh yes especially because I have an app that needs them! I just got a little overwhelmed with the number of operations to support but I'll get on it soon!

**Comment by praeclarum** [comment]
These were added in v2.0.0! https://github.com/praeclarum/ShaderGraphCoder/releases/tag/2.0.0
