### ISSUE TITLE
Texture coordinate V is upside down.

### ISSUE THREAD

**Issue by ynagatomo** [praeclarum/ShaderGraphCoder#5]
Thank you for fixing the texture issue. But I think the texture coordinate V may be upside down like showing below.

- ShaderGraphCoder: v2.0.0
- Xcode 15.4
- 
<img width="1699" alt="issue_texture" src="https://github.com/praeclarum/ShaderGraphCoder/assets/66309582/9337a4cc-7e47-4121-a907-3437ead23975">

**Comment by praeclarum** [comment]
Yeah this is an annoyance in USD shaders vs Metal (and the rest of the graphics world). For whatever reason, they decided to put 0,0 at the bottom left of a texture. Apple documents it (poorly) but I can't find the reference.

Sorry this is just a weird shader graph thing and not a bug in this library :-( Please make friends with the `oneMinus` operation.

**Comment by ynagatomo** [comment]
Understood. Thanks.
